# Twilio Account
TWILIO_ACCOUNT_SID = 'SET_YOUR_ACCOUNT_SID_HERE'

# Twilio Programmable Video Key
TWILIO_VIDEO_API_KEY_SID = 'SET_YOUR_PROGRAMMABLE_VIDEO_API_KEY_SID_HERE'
TWILIO_VIDEO_API_KEY_SECRET = 'SET_YOUR_PROGRAMMABLE_VIDEO_API_KEY_SECRET_HERE'
