language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install flake8
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8 --ignore=E501,E271,E272,W602,W504 --exclude=submodules"
