language: python
python:
  - "3.6"

install:
  - cd test_project
  - pip install flake8
  - pip install -r requirements.txt
  - cd ..

before_script:
  - python setup.py develop
  - cd test_project && python manage.py runserver 0.0.0.0:8000 && cd ..

script:
  - flake8 --ignore=E501,E271,E272,W602,W504
  - cd test_project && python manage.py test
